# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nBook.proto\"\x14\n\x04ISBN\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"s\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0e\n\x06rating\x18\x04 \x01(\x05\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\x12\x15\n\x05genre\x18\x06 \x01(\x0e\x32\x06.GENRE*<\n\x05GENRE\x12\x0b\n\x07\x46ICTION\x10\x00\x12\x0c\n\x08ROMANTIC\x10\x01\x12\x0c\n\x08THRILLER\x10\x02\x12\n\n\x06HORROR\x10\x03\x32H\n\rFunctionality\x12\x19\n\x07getBook\x12\x05.ISBN\x1a\x05.Book\"\x00\x12\x1c\n\ncreateBook\x12\x05.Book\x1a\x05.ISBN\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=153
  _GENRE._serialized_end=213
  _ISBN._serialized_start=14
  _ISBN._serialized_end=34
  _BOOK._serialized_start=36
  _BOOK._serialized_end=151
  _FUNCTIONALITY._serialized_start=215
  _FUNCTIONALITY._serialized_end=287
# @@protoc_insertion_point(module_scope)
