# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Inventory_system.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Book_pb2 as Book__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16Inventory_system.proto\x1a\nBook.proto\"m\n\rInventoryItem\x12\x18\n\x10Inventory_number\x18\t \x01(\t\x12\x17\n\x06status\x18\n \x01(\x0e\x32\x07.Status\x12\x1c\n\x0b\x62ook_object\x18\x0b \x01(\x0b\x32\x05.BookH\x00\x42\x0b\n\ttestoneof*\"\n\x06Status\x12\t\n\x05taken\x10\x00\x12\r\n\tavailable\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Inventory_system_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=149
  _STATUS._serialized_end=183
  _INVENTORYITEM._serialized_start=38
  _INVENTORYITEM._serialized_end=147
# @@protoc_insertion_point(module_scope)
