# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Book_pb2 as Book__pb2


class FunctionalityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getBook = channel.unary_unary(
                '/Functionality/getBook',
                request_serializer=Book__pb2.ISBN.SerializeToString,
                response_deserializer=Book__pb2.Book.FromString,
                )
        self.createBook = channel.unary_unary(
                '/Functionality/createBook',
                request_serializer=Book__pb2.Book.SerializeToString,
                response_deserializer=Book__pb2.ISBN.FromString,
                )


class FunctionalityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FunctionalityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getBook': grpc.unary_unary_rpc_method_handler(
                    servicer.getBook,
                    request_deserializer=Book__pb2.ISBN.FromString,
                    response_serializer=Book__pb2.Book.SerializeToString,
            ),
            'createBook': grpc.unary_unary_rpc_method_handler(
                    servicer.createBook,
                    request_deserializer=Book__pb2.Book.FromString,
                    response_serializer=Book__pb2.ISBN.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Functionality', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Functionality(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Functionality/getBook',
            Book__pb2.ISBN.SerializeToString,
            Book__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Functionality/createBook',
            Book__pb2.Book.SerializeToString,
            Book__pb2.ISBN.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
